// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconMdiCalendarBlank: typeof import('~icons/mdi/calendar-blank.jsx')['default']
  const IconMdiClockOutline: typeof import('~icons/mdi/clock-outline.jsx')['default']
  const IconMdiCog: typeof import('~icons/mdi/cog.jsx')['default']
  const IconMdiContentCopy: typeof import('~icons/mdi/content-copy.jsx')['default']
  const IconMdiContentPaste: typeof import('~icons/mdi/content-paste.jsx')['default']
  const IconMdiTimerOutline: typeof import('~icons/mdi/timer-outline.jsx')['default']
  const IconMdiTrashCan: typeof import('~icons/mdi/trash-can.jsx')['default']
  const IconMdiTrashCanOutline: typeof import('~icons/mdi/trash-can-outline.jsx')['default']
  const IconMdiUpdate: typeof import('~icons/mdi/update.jsx')['default']
}
export {}
