on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: prepare
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --no-tags --prune --depth=1 origin gh-pages
          rm -rf dist
          git worktree add -B gh-pages dist origin/gh-pages
          bun install

      - name: dist
        run: |
          rm -rf dist/**/*
          bun run build
          git --work-tree dist add --all
          git --work-tree dist commit -m "$(date +%Y%m%d)"
          git push origin HEAD:gh-pages --force
